### ISSUE TITLE
Engine does not reconnect to a restarted admin container

### ISSUE THREAD

**Issue by mkysel** [nuodb/nuodb-helm-charts#238]
**Describe the bug**
After a few seconds the admin gives up on waiting for the engine processes to reconnect. Logging looks like this
```
2021-08-12T18:06:23.390+0000 INFO  [admin-31wu94-nuodb-cluster0-0:processManagerScheduled29-1] ProcessManager Removing process with connectKey=1647498425067523578, startId=0, reason=Timed out (60000ms) awaiting connection from process: connectedState=PENDING_RECONNECT, removeAction=NONE, exitCode=null
2021-08-12T18:06:23.394+0000 INFO  [admin-31wu94-nuodb-cluster0-0:processManagerScheduled29-1] ProcessManager Removing process with connectKey=1026677207646886664, startId=1, reason=Timed out (60000ms) awaiting connection from process: connectedState=PENDING_RECONNECT, removeAction=NONE, exitCode=null
```

Or
```
2021-08-12T18:06:23.484+0000 WARN  [:RetryingRaftClientExec4-1] DomainProcessStateMachine admin-31wu94-nuodb-cluster0-0: No entry found for process with startId=1
```

Also
```
2021-08-12T18:07:15.393+0000 WARN  [admin-31wu94-nuodb-cluster0-0:tagServerExecutor31-2] ProcessManager Evicting unknown reconnecting process EngineNode{databaseName=demo, address=te-database-klkfbv-nuodb-cluster0-demo-69d99ff6bd-fkn7j, port=48006, type=TE, pid=44, state=RUNNING, nodeId=2, version=4.2.1.vee-3, ipAddress=10.1.5.157, hostname=te-database-klkfbv-nuodb-cluster0-demo-69d99ff6bd-fkn7j}
java.lang.NullPointerException: Expected to find durable process with startId=1
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:987)
	at com.nuodb.host.ProcessManager$AdminConnectionImpl.setAltAddress(ProcessManager.java:952)
	at com.nuodb.host.ProcessManager$AdminConnectionImpl.reconnect(ProcessManager.java:910)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.nuodb.server.TagMessageDispatcher.dispatch(TagMessageDispatcher.java:74)
	at com.nuodb.server.TagMessageDispatcher.dispatch(TagMessageDispatcher.java:44)
	at com.nuodb.server.BoundMessageDispatcher.dispatch(BoundMessageDispatcher.java:28)
	at com.nuodb.host.requests.RequestDispatcher.dispatch(RequestDispatcher.java:97)
	at com.nuodb.host.requests.RequestDispatcher.dispatch(RequestDispatcher.java:34)
	at com.nuodb.server.BoundMessageDispatcher.dispatch(BoundMessageDispatcher.java:28)
	at com.nuodb.server.Server.consumeMessages(Server.java:152)
	at com.nuodb.server.Server.lambda$acceptConnections$1(Server.java:121)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at com.nuodb.util.Threading$1.lambda$wrapTarget$0(Threading.java:29)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Context**
NuoDB Version: any
Helm Charts Version: any
Kubernetes Version: 1.15+
Environment: any

**To Reproduce**
1) Install the NuoDB admin
2) install the NuoDB database
3) restart one or more admin pods

**Expected behavior**
The engine reconnects successfully.

**Additional context**

**External Reference**
ZenDesk/JIRA numbers if available
JIRA: DB-33760

**Comment by adriansuarez** [comment]
This was fixed in 4.3 and 4.2.3. See the [release note](https://doc.nuodb.com/nuodb/4.2.x/release-notes/resolved-issues/#_resolved_in_nuodb_4_2_3):

> In Kubernetes or Docker container environments, a database process container may hang when performing DNS resolution. A database process connection timeout of 5 seconds has been set. Previously a timeout check was not implemented.
> This issue has been resolved.
